// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdeMaster.API.Data;

#nullable disable

namespace ProdeMaster.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260616112359_SeedDatosSeguridad")]
    partial class SeedDatosSeguridad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProdeMaster.API.Models.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "ADMIN_SEGURIDAD"
                        },
                        new
                        {
                            Id = 2,
                            Description = "ADMIN_NEGOCIO"
                        },
                        new
                        {
                            Id = 3,
                            Description = "PARTICIPAR_PRODE"
                        });
                });

            modelBuilder.Entity("ProdeMaster.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProdeMaster.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "79xh/2dupKgeYYOMqj9F3vVD9G/8/Dkqmg8QpYZS5KoendcDio8PWWAnoK+VXmz2Kc6Ms65p0dOWqHGeetDWEw==",
                            Salt = "aUJFXU52QxHD6iWZZK6k4Pv7S5SN3ewMjzbpT+JaavEUf2/HoqNqL8IKbW3uP/ab4gDnkk3/woRcb5g8jBCLhksiuYItiwyjkzlYCEEeB9LsdGlLxiE5FVTlQVl7KKF7MzPzbEaktMoELjC+YL8ZXD+1NKe00C2P0en3gO6lroE=",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("ProdeMaster.API.Models.UserPrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersPrivileges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrivilegeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            PrivilegeId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ProdeMaster.API.Models.RefreshToken", b =>
                {
                    b.HasOne("ProdeMaster.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProdeMaster.API.Models.UserPrivilege", b =>
                {
                    b.HasOne("ProdeMaster.API.Models.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdeMaster.API.Models.User", "User")
                        .WithMany("UserPrivileges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProdeMaster.API.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserPrivileges");
                });
#pragma warning restore 612, 618
        }
    }
}
